[build]
  base = "/"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--userconfig=./.npmrc"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
